export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_FATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    POST_CREATED: "PROFILE_POST_CREATED",
    POST_EDITED: "PROFILE_POST_EDITED",
    POST_DELETED: "PROFILE_POST_DELETED",
  },
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    DATA_DELETED: "POST_DATA_DELETED",
    POST_TO_EDITED: "POST_TO_EDITED",
    POST_EDIT_CANCELED: "POST_EDIT_CANCELED",
  },
};
